name: Playwright Tests

on:
  pull_request:

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  test:
    name: Playwright end-to-end tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up pnpm
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright Browsers
        run: pnpm exec playwright install chromium --no-shell

      - name: Run Playwright tests
        run: pnpm exec playwright test --forbid-only

      - name: Store Playwright test results
        uses: actions/upload-artifact@v7
        with:
          name: css-coverage
          path: css-coverage/*.json
          retention-days: 30

  css-coverage:
    name: Verify CSS Code Coverage
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up pnpm
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: css-coverage
          path: ./css-coverage

      - name: Analyze CSS Code Coverage
        run: pnpm css-coverage
        env:
          FORCE_COLOR: '3'
